# Author: Bradley R. Kinnard
"""LLM-powered research engine for IRONROOT.

This replaces the template-based system with actual LLM reasoning:
- Uses Grok for query understanding and web search
- Uses Semantic Scholar/arXiv for academic papers
- Synthesizes findings with proper citations
"""

import hashlib
import json
import os
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any

from ironroot.llm.client import LLMClient, get_llm_client
from ironroot.llm.grok import GrokClient
from ironroot.research.sources.arxiv import ArxivSource
from ironroot.research.sources.grok_search import GrokSearchSource
from ironroot.research.sources.semantic_scholar import SemanticScholarSource


@dataclass
class ResearchQuestion:
    """A research question generated by the LLM."""

    question: str
    rationale: str
    question_type: str  # factual, causal, comparative, evaluative
    priority: int
    search_terms: list[str]


@dataclass
class ResearchHypothesis:
    """A testable hypothesis about the research question."""

    statement: str
    prediction: str
    falsification_criteria: str
    evidence_needed: list[str]
    prior_probability: float


@dataclass
class Evidence:
    """A piece of evidence from research."""

    source_type: str  # "web", "academic", "arxiv"
    source_url: str
    source_title: str
    content: str
    relevance: str
    supports_hypothesis: bool | None
    data_hash: str


@dataclass
class ResearchFindings:
    """Complete research findings from the LLM engine."""

    original_query: str
    parsed_intent: str
    questions: list[ResearchQuestion]
    hypotheses: list[ResearchHypothesis]
    evidence: list[Evidence]
    synthesis: str
    confidence: float
    limitations: list[str]
    citations: list[dict]
    data_hash: str
    started_at: str
    completed_at: str


class LLMResearchEngine:
    """LLM-powered research engine.

    Pipeline:
    1. Parse query → understand intent, extract topics
    2. Generate questions → decompose into researchable sub-questions
    3. Form hypotheses → create testable predictions
    4. Gather evidence → search web, academic sources
    5. Synthesize → combine findings into coherent answer
    """

    def __init__(self):
        self._llm: LLMClient | None = None
        self._grok: GrokClient | None = None
        self._semantic_scholar: SemanticScholarSource | None = None
        self._arxiv: ArxivSource | None = None
        self._grok_search: GrokSearchSource | None = None

    async def _get_llm(self) -> LLMClient:
        """Get the LLM client."""
        if self._llm is None:
            self._llm = get_llm_client()
        return self._llm

    async def _get_grok(self) -> GrokClient | None:
        """Get Grok client for web search."""
        if self._grok is None and os.getenv("XAI_API_KEY"):
            self._grok = GrokClient()
        return self._grok

    async def _get_sources(
        self,
    ) -> tuple[SemanticScholarSource, ArxivSource, GrokSearchSource | None]:
        """Get data source clients."""
        if self._semantic_scholar is None:
            self._semantic_scholar = SemanticScholarSource()
        if self._arxiv is None:
            self._arxiv = ArxivSource()
        if self._grok_search is None:
            grok = await self._get_grok()
            if grok:
                self._grok_search = GrokSearchSource(grok)
        return self._semantic_scholar, self._arxiv, self._grok_search

    async def research(
        self,
        query: str,
        max_questions: int = 5,
        max_hypotheses: int = 3,
        progress_callback: Any = None,
    ) -> ResearchFindings:
        """Run a full research campaign on the query."""
        started_at = datetime.now(UTC).isoformat()

        def update(phase: str, percent: int, msg: str):
            if progress_callback:
                progress_callback(phase, percent, msg)

        # Phase 1: Parse query and understand intent
        update("parsing", 5, "Analyzing your research query...")
        parsed = await self._parse_query(query)

        # Phase 2: Generate research questions
        update("questions", 20, "Generating research questions...")
        questions = await self._generate_questions(query, parsed, max_questions)

        # Phase 3: Form hypotheses
        update("hypotheses", 35, f"Forming hypotheses from {len(questions)} questions...")
        hypotheses = await self._form_hypotheses(query, questions, max_hypotheses)

        # Phase 4: Gather evidence
        update("evidence", 50, "Searching for evidence...")
        evidence, citations = await self._gather_evidence(query, questions, hypotheses)

        # Phase 5: Synthesize findings
        update("synthesis", 80, "Synthesizing findings...")
        synthesis, confidence, limitations = await self._synthesize(
            query, questions, hypotheses, evidence
        )

        # Complete
        completed_at = datetime.now(UTC).isoformat()
        data_hash = hashlib.sha256(
            json.dumps(
                {
                    "query": query,
                    "questions": [q.question for q in questions],
                    "hypotheses": [h.statement for h in hypotheses],
                    "synthesis": synthesis,
                }
            ).encode()
        ).hexdigest()[:16]

        return ResearchFindings(
            original_query=query,
            parsed_intent=parsed.get("intent", "exploration"),
            questions=questions,
            hypotheses=hypotheses,
            evidence=evidence,
            synthesis=synthesis,
            confidence=confidence,
            limitations=limitations,
            citations=citations,
            data_hash=data_hash,
            started_at=started_at,
            completed_at=completed_at,
        )

    async def _parse_query(self, query: str) -> dict:
        """Parse the research query to understand intent."""
        llm = await self._get_llm()

        system = """You are a research query analyzer. Parse the user's query and extract:
        1. Primary intent (factual, causal, comparative, evaluative, exploratory)
        2. Main topics and concepts
        3. Key entities or systems mentioned
        4. What type of answer they're looking for

        Respond in JSON format."""

        prompt = f"""Analyze this research query:

"{query}"

Respond with JSON:
{{
    "intent": "causal|comparative|evaluative|factual|exploratory",
    "topics": ["topic1", "topic2"],
    "entities": ["entity1", "entity2"],
    "answer_type": "explanation|comparison|evaluation|fact|overview",
    "domain": "technology|science|business|society|other"
}}"""

        response = await llm.complete(prompt, system=system, temperature=0.1)

        try:
            # Try to parse JSON from response
            content = response.content
            # Find JSON in response
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                return json.loads(content[start:end])
        except json.JSONDecodeError:
            pass

        # Fallback
        return {
            "intent": "exploratory",
            "topics": [query[:50]],
            "entities": [],
            "answer_type": "overview",
            "domain": "other",
        }

    async def _generate_questions(
        self,
        query: str,
        parsed: dict,
        max_questions: int,
    ) -> list[ResearchQuestion]:
        """Generate research questions from the query."""
        llm = await self._get_llm()

        system = """You are a research question generator. Create specific, answerable research questions
        that will help comprehensively address the user's query. Each question should be:
        - Specific enough to research
        - Answerable with evidence
        - Contributing to the overall query

        Respond in JSON format."""

        prompt = f"""Original query: "{query}"

Parsed intent: {parsed.get('intent', 'exploratory')}
Topics: {parsed.get('topics', [])}

Generate {max_questions} research questions that would help answer this query.

Respond with JSON:
{{
    "questions": [
        {{
            "question": "The research question",
            "rationale": "Why this helps answer the query",
            "type": "factual|causal|comparative|evaluative",
            "priority": 1,
            "search_terms": ["term1", "term2"]
        }}
    ]
}}"""

        response = await llm.complete(prompt, system=system, temperature=0.3)

        questions = []
        try:
            content = response.content
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(content[start:end])
                for q in data.get("questions", [])[:max_questions]:
                    questions.append(
                        ResearchQuestion(
                            question=q.get("question", ""),
                            rationale=q.get("rationale", ""),
                            question_type=q.get("type", "factual"),
                            priority=q.get("priority", 1),
                            search_terms=q.get("search_terms", []),
                        )
                    )
        except json.JSONDecodeError:
            # Fallback: create basic question from query
            questions.append(
                ResearchQuestion(
                    question=query,
                    rationale="Direct investigation of the query",
                    question_type="exploratory",
                    priority=1,
                    search_terms=query.split()[:5],
                )
            )

        return questions

    async def _form_hypotheses(
        self,
        query: str,
        questions: list[ResearchQuestion],
        max_hypotheses: int,
    ) -> list[ResearchHypothesis]:
        """Form testable hypotheses from the research questions."""
        llm = await self._get_llm()

        questions_text = "\n".join(f"- {q.question}" for q in questions)

        system = """You are a hypothesis generator. Create testable hypotheses that:
        - Make specific predictions
        - Can be falsified with evidence
        - Address the research questions

        Respond in JSON format."""

        prompt = f"""Original query: "{query}"

Research questions:
{questions_text}

Generate {max_hypotheses} testable hypotheses.

Respond with JSON:
{{
    "hypotheses": [
        {{
            "statement": "The hypothesis statement",
            "prediction": "What we would observe if true",
            "falsification": "What would disprove this",
            "evidence_needed": ["type of evidence 1", "type of evidence 2"],
            "prior_probability": 0.5
        }}
    ]
}}"""

        response = await llm.complete(prompt, system=system, temperature=0.3)

        hypotheses = []
        try:
            content = response.content
            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(content[start:end])
                for h in data.get("hypotheses", [])[:max_hypotheses]:
                    hypotheses.append(
                        ResearchHypothesis(
                            statement=h.get("statement", ""),
                            prediction=h.get("prediction", ""),
                            falsification_criteria=h.get("falsification", ""),
                            evidence_needed=h.get("evidence_needed", []),
                            prior_probability=h.get("prior_probability", 0.5),
                        )
                    )
        except json.JSONDecodeError:
            pass

        return hypotheses

    async def _gather_evidence(
        self,
        query: str,
        questions: list[ResearchQuestion],
        hypotheses: list[ResearchHypothesis],
    ) -> tuple[list[Evidence], list[dict]]:
        """Gather evidence from multiple sources."""
        import asyncio

        evidence = []
        all_citations = []

        semantic_scholar, arxiv, grok_search = await self._get_sources()

        # Collect search terms from questions
        search_terms = set()
        for q in questions:
            search_terms.update(q.search_terms)
        search_terms.add(query[:100])  # Add truncated original query

        # 1. Search academic papers (Semantic Scholar) - with rate limit handling
        try:
            term = " ".join(list(search_terms)[:3])  # Single query to avoid rate limits
            result = await semantic_scholar.search(term, limit=5)
            for paper in result.papers[:5]:
                evidence.append(
                    Evidence(
                        source_type="academic",
                        source_url=paper.url,
                        source_title=paper.title,
                        content=paper.abstract or "",
                        relevance="Academic paper from Semantic Scholar",
                        supports_hypothesis=None,
                        data_hash=hashlib.sha256(paper.paper_id.encode()).hexdigest()[:16],
                    )
                )
                all_citations.append(
                    {
                        "url": paper.url,
                        "title": paper.title,
                        "type": "academic",
                        "year": paper.year,
                        "citations": paper.citation_count,
                    }
                )
        except Exception as e:
            # Rate limited or other error - continue with other sources
            if "429" in str(e):
                evidence.append(
                    Evidence(
                        source_type="info",
                        source_url="",
                        source_title="Semantic Scholar Rate Limited",
                        content="Rate limit reached - using other sources",
                        relevance="Info",
                        supports_hypothesis=None,
                        data_hash="ratelimit",
                    )
                )
            else:
                evidence.append(
                    Evidence(
                        source_type="error",
                        source_url="",
                        source_title="Semantic Scholar Error",
                        content=f"Could not fetch academic papers: {e}",
                        relevance="Error",
                        supports_hypothesis=None,
                        data_hash="error",
                    )
                )

        # Small delay to respect rate limits
        await asyncio.sleep(0.5)

        # 2. Search arXiv preprints
        try:
            arxiv_query = " ".join(list(search_terms)[:3])
            result = await arxiv.search(arxiv_query, max_results=5)
            for paper in result.papers[:5]:
                evidence.append(
                    Evidence(
                        source_type="arxiv",
                        source_url=paper.abs_url,
                        source_title=paper.title,
                        content=paper.abstract[:500] if paper.abstract else "",
                        relevance="Preprint from arXiv",
                        supports_hypothesis=None,
                        data_hash=hashlib.sha256(paper.arxiv_id.encode()).hexdigest()[:16],
                    )
                )
                all_citations.append(
                    {
                        "url": paper.abs_url,
                        "title": paper.title,
                        "type": "arxiv",
                        "arxiv_id": paper.arxiv_id,
                        "categories": paper.categories,
                    }
                )
        except Exception as e:
            evidence.append(
                Evidence(
                    source_type="error",
                    source_url="",
                    source_title="arXiv Error",
                    content=f"Could not fetch arXiv papers: {e}",
                    relevance="Error",
                    supports_hypothesis=None,
                    data_hash="error",
                )
            )

        # 3. Web search via Grok (if available)
        if grok_search:
            try:
                result = await grok_search.research_question(query)
                evidence.append(
                    Evidence(
                        source_type="web",
                        source_url="grok_web_search",
                        source_title="Grok Web Search Results",
                        content=result.content,
                        relevance="Real-time web search with citations",
                        supports_hypothesis=None,
                        data_hash=result.data_hash,
                    )
                )
                for cite in result.citations:
                    all_citations.append(
                        {
                            "url": cite.get("url", ""),
                            "title": cite.get("title", ""),
                            "type": "web",
                            "snippet": cite.get("snippet", ""),
                        }
                    )
            except Exception as e:
                evidence.append(
                    Evidence(
                        source_type="error",
                        source_url="",
                        source_title="Web Search Error",
                        content=f"Could not perform web search: {e}",
                        relevance="Error",
                        supports_hypothesis=None,
                        data_hash="error",
                    )
                )

        return evidence, all_citations

    async def _synthesize(
        self,
        query: str,
        questions: list[ResearchQuestion],
        hypotheses: list[ResearchHypothesis],
        evidence: list[Evidence],
    ) -> tuple[str, float, list[str]]:
        """Synthesize findings - ONLY reporting what evidence actually says.

        CRITICAL: This must never generate unverified claims or statistics.
        Every claim must be traceable to a specific source.
        """
        llm = await self._get_llm()

        # Build evidence with source attribution
        evidence_text = []
        valid_sources = 0
        for e in evidence:
            if e.source_type not in ("error", "info"):
                valid_sources += 1
                evidence_text.append(
                    f"SOURCE [{valid_sources}]: {e.source_title}\n"
                    f"URL: {e.source_url}\n"
                    f"Type: {e.source_type}\n"
                    f"Content: {e.content[:500]}\n"
                )

        if not evidence_text:
            # No valid evidence - be explicit about this
            return (
                "## Research Findings\n\n"
                "**No verifiable evidence was found for this query.**\n\n"
                "The academic databases (Semantic Scholar, arXiv) did not return "
                "relevant papers on this specific topic. This could mean:\n"
                "- The topic is too novel/emerging for published research\n"
                "- The query terms need refinement\n"
                "- The topic requires different data sources\n\n"
                "**Recommendation:** Try reformulating the query or check specialized databases.",
                0.0,
                ["No evidence found in searched databases"],
            )

        evidence_summary = "\n---\n".join(evidence_text)

        system = """You are a STRICT research reporter. Your ONLY job is to report what the evidence says.

CRITICAL RULES:
1. NEVER generate statistics, percentages, or numbers unless they appear VERBATIM in a source
2. NEVER claim "studies show X%" unless you quote the exact study with that number
3. ALWAYS attribute claims to specific sources using [SOURCE N] citations
4. If no source supports a claim, state "NO EVIDENCE FOUND" - do NOT fabricate
5. If sources are limited or tangentially related, SAY SO explicitly
6. It's better to say "insufficient evidence" than to make up plausible-sounding claims

You are building a VERIFIABLE research record. Every claim must be traceable."""

        prompt = f"""Original Query: "{query}"

AVAILABLE EVIDENCE (cite by [SOURCE N]):
{evidence_summary}

Based ONLY on the evidence above, produce a research report:

## DIRECT FINDINGS
What do these specific sources actually say about the query? Use [SOURCE N] citations.
If a source doesn't directly address the query, say so.

## EVIDENCE GAPS
What aspects of the query are NOT addressed by the available evidence?
Be explicit about what we could NOT find.

## VERIFIED CLAIMS
List ONLY claims that can be directly traced to a source:
- [SOURCE N]: "quote or paraphrase with attribution"

## UNVERIFIABLE ASPECTS
What parts of the query require more research or different sources?

## ASSESSMENT
Given the evidence quality and coverage, how well can we answer the original query?
(Be honest if evidence is weak, tangential, or insufficient)"""

        response = await llm.complete(prompt, system=system, temperature=0.1, max_tokens=2048)

        content = response.content

        # Calculate confidence based on evidence quality, not LLM confidence
        # This should be evidence-based, not hallucinated
        if valid_sources >= 5:
            confidence = 0.7
        elif valid_sources >= 3:
            confidence = 0.5
        elif valid_sources >= 1:
            confidence = 0.3
        else:
            confidence = 0.0

        # Extract limitations from the response
        limitations = [
            f"Based on {valid_sources} sources from academic databases",
            "Claims limited to what sources explicitly state",
        ]

        if "EVIDENCE GAPS" in content:
            gaps_section = content.split("EVIDENCE GAPS")[-1].split("##")[0]
            for line in gaps_section.split("\n"):
                line = line.strip()
                if line.startswith("-") or line.startswith("•"):
                    limitations.append(line[1:].strip())

        return content, confidence, limitations

    async def close(self) -> None:
        """Clean up resources."""
        if self._semantic_scholar:
            await self._semantic_scholar.close()
        if self._arxiv:
            await self._arxiv.close()
        if self._grok_search:
            await self._grok_search.close()
        if self._grok:
            await self._grok.close()
